name: Test

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        ruby:
          - '2.7'
          - '3.0'
          - head

        activerecord:
          - '6.0'
          - '6.1'
          - '7.0'

    runs-on: ubuntu-latest

    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/activerecord_${{ matrix.activerecord }}.gemfile

    steps:
    - uses: actions/checkout@v2

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - run: bundle exec rspec
