name: Test

on:
  push:
  pull_request:

jobs:
  gemfiles:
    runs-on: ubuntu-latest

    outputs:
      value: ${{ steps.to-json.outputs.value }}

    steps:
      - uses: actions/checkout@v2

      - id: to-json
        run: |
          gemfiles=$(ls gemfiles/*.gemfile | jq --raw-input --slurp --compact-output '. / "\n" - [""]')
          echo "::set-output name=value::$gemfiles"

  test:
    needs: gemfiles

    strategy:
      matrix:
        ruby:
          - 2.7
          - 3.0
          - head

        gemfile: ${{ fromJson(needs.gemfiles.outputs.value) }}

    runs-on: ubuntu-latest

    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}

    steps:
    - uses: actions/checkout@v2

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - run: bundle exec rspec
