name: Test

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        ruby:
          - 2.7
          - 3.0
          - head

        factory_bot:
          - ~> 5.0
          - ~> 6.0

        activerecord:
          - ~> 6.0.0
          - ~> 6.1.0
          - ~> 7.0.0.alpha

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: |
        echo "gem 'factory_bot', '${{ matrix.factory_bot }}'" >> Gemfile
        sed --in-place "s/gem 'activerecord'/gem 'activerecord', '${{ matrix.activerecord }}'/" Gemfile

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - run: bundle exec rspec
