name: Test

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        ruby:
          - 2.7
          - 3.0
          - head
        factory_bot:
          - ~> 6.0
        activerecord:
          - ~> 6.1.0

        include:
          - ruby: 3.0
            factory_bot: ~> 5.0 # previous version
            activerecord: ~> 6.1.0
          - ruby: 3.0
            factory_bot: ~> 6.0
            activerecord: ~> 6.0.0 # previous version
          - ruby: 3.0
            factory_bot: ~> 6.0
            activerecord: ~> 7.0.0.alpha # pre-release version

    runs-on: ubuntu-latest

    env:
      ACTIVERECORD: ${{ matrix.activerecord }}
      FACTORY_BOT: ${{ matrix.factory_bot }}

    steps:
    - uses: actions/checkout@v2

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - run: bundle exec rspec
